### ISSUE TITLE
Small typo in the paper

### ISSUE THREAD

**Issue by maximzubkov** [skeletondyh/GRED#1]
Hello, GRED team

Thank you for the awesome work you did! I might notice one small typo in your paper, nothing too serious, just a dimensions mismatch in one of the proofs. Am I correct that the index should be K+1 instead of d_s?

<img width="686" alt="Screenshot 2023-12-06 at 18 26 08" src="https://github.com/skeletondyh/GRED/assets/47659865/564d91ee-1d06-4152-9b63-e090edb828cc">

**Comment by skeletondyh** [comment]
Thank you for catching that! 
Yes, you are right. We'll correct it in an updated version.

**Comment by maximzubkov** [comment]
Great, will close the issue then
